### ISSUE TITLE
box collections:add web_link not functioning

### ISSUE THREAD

**Issue by tcranger1** [box/boxcli#130]
Hi,

Thank you for putting together this fantastic tool.  Our organization's implementation of Box would not have been as successful as it's been so far without the use of this tool.  

We are experiencing an issue with the "box collections:add" command.  Whenever we try to add a type of "web_link" we receive the following error:
**box : Cannot read property 'name' of undefined** 

The syntax we are using is:
**box collections:add web_link <id#> <id#> --as-user <id#>**
 
We do not receive this error when we attempt to add files and folders to a collection.  Our partners at Box have confirmed this issue on their end as well.  

Thanks again!

**Comment by mattwiller** [comment]
@tcranger1 Thanks for letting us know!  The fix for this will be in two parts: we'll add the required web link functionality to our Node.js SDK (which the CLI is built on top of) and then add support in the CLI once the Node.js SDK is updated.  I'll update this ticket when the work on the Node.js SDK is finished and we're finishing everything up here in the CLI.

**Comment by tcranger1** [comment]
@mattwiller Much appreciated!  Thanks again!!

Cheers!

**Comment by mattwiller** [comment]
@tcranger1 The fix for this issue is included in v2.2.0 of the CLI, which we released yesterday.  Please give it a try and let us know if you run into any other issues!

**Comment by tcranger1** [comment]
Thank you.  I can confirm that this feature is now working as expected.
Much appreciated!
