### ISSUE TITLE
Box Users -m flag 

### ISSUE THREAD

**Issue by dann815** [box/boxcli#137]
I would like to retrieve a list of all managed users.

The Users command with the -m flag is not skipping App Users
`box users --managed-users --yes --fields=id,name,login --save-to-file-path=./inputs/UserList.json`

**Comment by mattwiller** [comment]
@dann815 This should maybe be fixed in the API (which returns the mixed collection of Managed and App users when you pass the query parameter), but we could also add post-filtering of the collection in the CLI to accomplish the same effect.  We'll add it the backlog, but if you need it more quickly you're of course free to submit a PR!

**Comment by mhagmajer** [comment]
Thanks for posting @dann815. External users will not be included in the result unless you include `--filter` option and set it to the login of the external user you'd like to fetch. See more at: https://developer.box.com/reference/get-users/#param-filter_term
