### ISSUE TITLE
include total count param 

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#158]
- [ X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
API results does not include the total_count field in the returned results.
Eg: box users:list --json

box CLI v1 used to include this in the results.

### 
Box CLI: v2.2
Operating System: Windows 10, MacOS X

### Steps to Reproduce
Run any command that return results as a list
box users:list --json
box events --json

### Error Message, Including Stack Trace
n/a

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@Band-Aid Unfortunately, I think adding this to the output would be a breaking change.  The JSON output for commands like `box users:list` is currently an array; we can't add `total_count` to it without changing the output type to an object.  The CLI always returns the full set of results; you should be able to parse or grep the JSON and count the number of elements in the array to get the total count.

If you use a tool like [jq](https://stedolan.github.io/jq/), you can do something like this to parse the JSON and get the correct length:
```
box users --json | jq '. | length'
```

Otherwise, since every user should have a `"type": "user"` line in the JSON, you could use `grep` to get the count like this:
```
box users --json | grep '"type": "user"' | wc -l
```
