### ISSUE TITLE
box collaborations:update sends non-error output to stderr

### ISSUE THREAD

**Issue by ispcolohost** [box/boxcli#173]
- [X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
"box collaborations:update" sends its valid output to stderr instead of stdout.  For example:

 box collaborations:update 18252770368 -r owner --json 2>/dev/null
 (nothing)

versus

 box collaborations:update 18252961652 -r owner --json
Collaborator successfully upgraded to owner.

The command is not failing, so the output should be to stdout like all the other commands.  It is obviously also not producing the output in json format even though the flag has been given.

### Versions Used
Box CLI: @box/cli/2.4.0 darwin-x64 node-v12.6.0
Operating System: MacOS Mojave 10.15

### Steps to Reproduce
See bug description

### Error Message, Including Stack Trace

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @ispcolohost,
Thanks for reporting this issue.  It definitely sounds like a bug in the Box CLI.  I'll take a look at it and see what I find.  Thanks!
~Patrick

**Comment by ispcolohost** [comment]
It may be any box collaborations:* commands, as I think it happened with :delete too.

**Comment by PJSimon** [comment]
Hi @ispcolohost,
I just wanted to update you that we were a little slow to respond last week due to the release of our iOS SDK.  We're catching up on things and will get back to you soon on this.  Thanks for your patience!
~Patrick

**Comment by nidoran** [comment]
Hi @ispcolohost ,
You've come across two things in the cli:
1) Some commands don't output a JSON object because one is not returned from the Box API response. When a collab's role is changed to owner, the API returns 204 - no response body, so the CLI will not print any collab object either. Same with deleting a collab, the API returns 204 - no response body, so the CLI has no JSON object to print out. For these kinds of commands, the absence of errors means it was successful (along with the informational output you see).
2) Some informational data is printed to stderr, not stdout. The `--quiet` flag will suppress this non-error output for stderr.

Let us know if there are further questions.
