### ISSUE TITLE
npm WARN deprecated request@2.88.2

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#182]
- [X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Do you think we should consider replacing requests with an alternative library?

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### Versions Used
n/a

### Steps to Reproduce
build boxcli from source

### Error Message, Including Stack Trace
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @Band-Aid ,

Thanks for calling this out!  We'll take a look, ASAP and get back to you!

Thanks,

Patrick

**Comment by PJSimon** [comment]
Closed by accident.

**Comment by sujaygarlanka** [comment]
@Band-Aid The CLI uses our Node SDK. Since our Node SDK uses the recently deprecated `request` library, the CLI uses it as well. When we upgrade the Node SDK, the CLI will be upgraded as well. We have a ticket open for our Node SDK to use a non-deprecated networking library. Will keep you up to date on any progress made.

**Comment by sujaygarlanka** [comment]
SDK-1381
