### ISSUE TITLE
Email notification when bulk transfers or deletions finish within the Box CLI or API.

### ISSUE THREAD

**Issue by jkhancock31** [box/boxcli#421]
### Is your feature request related to a problem? Please describe.
When bulk transfers or deletions are performed, the Box Admin or Co-Admin account performing the transfers or deletions is not notified when the command is completed.

### Describe the solution you'd like
The Box CLI and API's to send a notification to either the logged in account or be able to set an email address to send notifications to once bulk commands are completed.

### Describe alternatives you've considered
The only alternate solution is visually monitoring the progress bar.

**Comment by arjankowski** [comment]
Hi @jkhancock31,

Currently our APIs are not aware of bulk calls as they are executed on the caller side. For this reason, it is not possible to send an e-mail notification after its completion.

If there was a dedicated endpoint in the API that would send a custom notification when invoked, it could be easily integrated into our boxcli.
We could integrate it into a bulk operation with an additional flag that would specify whether or not it should notify the user upon completion.

Please post your suggestion on the boxpule [here](https://pulse.box.com/forums/909778-help-shape-the-future-of-box?category_id=353563) so that the right team can consider this change in future sprints.
