### ISSUE TITLE
Can't query metadata

### ISSUE THREAD

**Issue by c-rei** [box/boxcli#494]
I want to get some metadata with CLI like below, and I got some error.
I am a owner of the folder which queried.

>box metadata-query enterprise_12345.template4 12345678900 --as-user=22222222

Unexpected API Response [403 Forbidden | 0a85ec5347cca63c9433d9a39c20127b1.0a85ec5347cca63c9433d9a39c20127b1] metadata_query_restricted - Metadata Query API found either too many items outside the ancestor folder or too many inaccessible items matching the query.

### Versions Used
Box CLI: @box/cli/3.11.0 win32-x64 node-v14.19.3
Operating System: Windows 10

So, I want to known what's wrong with my CLI?
Thanks any response.

**Comment by mwwoda** [comment]
Hi @c-rei 
The error appears to be coming from the API itself. There are two possible causes for this error, as the error message indicates. Either the query returns too many results, or you don't have permissions to all items in the result set. For more information, see https://developer.box.com/guides/metadata/queries/limitations/#recommended-result-set-size. I recommend narrowing down the query and making sure that the user has the correct permissions set.

**Comment by mwwoda** [comment]
According to the documentation, you should have Previewer permissions on all elements of the result set. The CLI in this case only returns an API response (you could probably get the same error by making same call with cURL. My guess is that the problem lies either in the API or in the specific configuration. You can try contacting support on our forum https://forum.box.com/latest if you think the problem is related to the API.
