### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by w9y9x** [box/boxcli#537]
- [ √] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [√ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [√ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ √] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.
Reference Links：https://github.com/box/boxcli/issues/276

### Description of the Issue
I installed box cli in linux environment and configured config.json, but when I run the box users:get command, an error message appears: self-signed certificate in certificate chain, but the box version is normal. How can I bypass SSL verification, or where should I download the certificate from?

### Steps to Reproduce
1. npm install --global @box/cli
2. box configure:environments:add /root/config.json
3. box version
4. box users:get
self-signed certificate in certificate chain

### Expected Behavior
User information should appear normally

### Error Message, Including Stack Trace
self signed certificate in certificate chain

### Screenshots
<img width="521" alt="error" src="https://github.com/box/boxcli/assets/76726783/c4a7bc7f-3cb3-473a-9949-eaac207c3952">

### Versions Used
Box CLI: @box/cli/3.14.1 linux-x64 node-v18.10.0
Operating System: Red Hat Enterprise Linux release 8.10 (Ootpa)

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/boxcli/search?type=Issues

**Comment by arjankowski** [comment]
Hi @w9y9x,

The issue you're experiencing is most likely due to the proxy server using its own certificate, which is not trusted.
To resolve this issue, you can try one of the following options:

1) **Add an environment variable:**
Set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0`, as described here: [GitHub Issue #276.](https://github.com/box/boxcli/issues/276)

2) **Add the self-signed certificate to trusted certificates:**
Download the self-signed certificate and add it to Node.js trusted certificates by setting the following environment variable:
```
export NODE_EXTRA_CA_CERTS=/path/to/certificate.pem
```

The best way to obtain the certificate is to request it from your proxy server administrator. 
If this is not possible, you can try to download it yourself by running the command:

```
openssl s_client -connect <PROXY_SERVER_ADDRESS:PORT> -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > downloaded_cert.pem
```
In your case, it should look like this:

```
openssl s_client -connect PITC-Zscaler-China-Shanghai-IDC-HC.proxy.corporate.ge.com:80 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > downloaded_cert.pem
```

I hope this helps!
Artur

**Comment by w9y9x** [comment]
thank you for your reply
I tried setting the environment variable NODE_TLS_REJECT_UNAUTHORIZED=0, but it didn't seem to solve my problem
<img width="681" alt="error" src="https://github.com/box/boxcli/assets/76726783/425da240-c144-47d4-ab45-c27b4599771e">


I also tried adding the trusted certificate in nodejs, but it didn't seem to work. Is there any other suitable solution?
<img width="682" alt="option2_1" src="https://github.com/box/boxcli/assets/76726783/992a2257-7270-4f61-8991-3432718aae6a">
<img width="593" alt="option2_2" src="https://github.com/box/boxcli/assets/76726783/61c6adfa-b698-4277-9fb3-211638a1a16a">

**Comment by lukaszsocha2** [comment]
Hi @w9y9x,
can you ask your proxy provider for the root self-signed certificate and then try to apply it again?
Best,
@lukaszsocha2

**Comment by w9y9x** [comment]
Do you know where I can get the self-signed certificate for box cli if I'm not using a proxy?
<img width="502" alt="error" src="https://github.com/user-attachments/assets/63f0be91-511e-4728-a867-c8c2d04bbdb1">
