### ISSUE TITLE
I can not request the updated_at date for files

### ISSUE THREAD

**Issue by cschaba** [box/boxcli#540]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I want to create a list of files for a folder and what to output the `updated_at` field, but it's missing in the output.  Other fields, like `created_at` are shown correctly.

### Steps to Reproduce

```
box folders:items --as-user=123456789 --sort=date --json --fields=type,id,name,created_at,updated_at 123456789
...
    {
        "type": "file",
        "id": "123456789",
        "name": "Document.pdf",
        "created_at": "2020-09-01T02:59:09-07:00"
    },
...
```

I wonder also where to find a complete list of valid fields, I took the example output of https://developer.box.com/reference/resources/file-request/ as reference, is that the right source?

I also wonder which date field for the `--sort=date` option is used.  Is it `created_at` or `updated_at`?

### Expected Behavior

I would expect the `updated_at` field in the output. 

### Versions Used
Box CLI: @box/cli/3.14.1 darwin-x64 node-v14.19.3
Operating System: MacOS 15.0

**Comment by arjankowski** [comment]
Hi @cschaba,

The command you are performing corresponds to this [API call](https://developer.box.com/reference/get-folders-id-items/)

If you want to obtain a specific field that is not returned by default, you need to specify it in the `fields` parameter.
As for the possible `fields` that can be passed in the fields parameter, they can be any of the available fields of the returned resources.

Since **List items in folder** returns three resources `file`,  `folder`, `weblink`, you can find the possible fields here:
**file**: https://developer.box.com/reference/resources/file--full/
**folder**: https://developer.box.com/reference/resources/folder--full/
**weblink**: https://developer.box.com/reference/resources/web-link/

In your case, since you are interested in the `update date`, you need to pass the corresponding field which is `modified_at` described [here.](https://developer.box.com/reference/resources/file--full/#param-modified_at)

So the final query should look like this:

```
box folders:items --as-user=123456789 --sort=date --json --fields=type,id,name,created_at,modified_at 123456789
```

Regards,
Artur

**Comment by arjankowski** [comment]
@cschaba
I'm glad that this solved your problem.

When it comes to `--sort=date`It looks like it uses the `created_at` date.
